'------------------------------------
' Macros & definitions
'-----------------------------------
' Default settings
'-----------------------------------
' left to right direction 'does not work for sequence diagrams :-(
hide circle
hide empty members
hide methods	

'Colors => see http://plantuml.com/color
'skinparam monochrome true
'skinparam monochrome reverse
'skinparam handwritten true
!define BLUE Skyblue
!define YELLOW Lightyellow
!define GREEN Lightgreen

skinparam defaultTextAlignment center

skinparam storage {
  BackgroundColor YELLOW
}

skinparam node {
  BackgroundColor BLUE
}

skinparam rectangle {
  BackgroundColor GREEN
  BorderColor Black
}

skinparam arrow {
    Color<<ac>> Black
}

skinparam package {
	BackgroundColor empty
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName TrebuchetMS
}
skinparam roundcorner 10

skinparam class {
	BackgroundColor AliceBlue
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName TrebuchetMS
}
skinparam arrow {
    MessageAlign center
}

' Usefull functions
'-----------------------------------
!define ressource(id,label) storage label <<Ressource>> as id
!define sae(id,label) node label <<SAÉ>> as id





